#!/usr/bin/env python

from __future__ import print_function

import argparse


def sort_sensitivity():

    """Sorts the sensitivity from the osmABTS output"""

    parser = argparse.ArgumentParser(
        description="Sorts the sensitivity data from osmABTS"
        )
    parser.add_argument(
        'file', metavar='FILE', type=argparse.FileType('r'),
        help='The output file of osmABTS'
        )
    parser.add_argument(
        '--number', '-n', type=int, default=15,
        help='The number of most sensitive edge to print'
        )
    args = parser.parse_args()

    
    edges = []
    for line in args.file:

        if line[0:4] != 'SA: ':
            continue
        else:
            fields = line[4:].split('/')
            edges.append(
                (fields[0], fields[1], fields[2], float(fields[3]), float(fields[4]))
                )

    edges.sort(key=lambda edge: edge[4], reverse=True)

    for edge in edges[0:args.number]:
        print(' %s / %s / %s / %f ' % (edge[0], edge[1], edge[2], edge[4]))
    
    return 0


if __name__ == '__main__':
    sort_sensitivity()







